### ISSUE TITLE
I'm getting `NameError: name 'join_group_single' is not defined`

### ISSUE THREAD

**Issue by MotorCityCobra** [philtrade/Ddip#3]
I'm using fastai1 (fastai version 1.0.64.dev0) and trying to implement Ddip in the course-v3 lessons.   

The following gets executed in the Jupyter Notebook cell with no problems
`%reload_ext autoreload`
`%autoreload 2`
`%matplotlib inline`
`%load_ext Ddip`
`%reload_ext Ddip`

But the last line  
`%makedip -g all -a fastai_v1 --verbose False`

Gives me the error...  

    [0:execute]: 
    ---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)    <ipython-input-1-85059193315d> in <module>
    ----> 1 r = join_group_single(g_rank=g_rank, l_rank=l_rank, gpu=gpu, ws=ws)
    NameError: name 'join_group_single' is not defined

    [1:execute]: 
    ---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)    <ipython-input-1-85059193315d> in <module>
    ----> 1 r = join_group_single(g_rank=g_rank, l_rank=l_rank, gpu=gpu, ws=ws)
    NameError: name 'join_group_single' is not defined

**Comment by philtrade** [comment]
Hello @MotorCityCobra , thank you for reporting the problem.  It seems to be a race condition that wasn't obvious in my own dev environment -- fixed, please try the HEAD, and close the issue if it works for you.  Thank you!
